@baseUrl = http://localhost:3001

POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
    "email": "chef@test.com",
    "password": "password123",
    "nickname": "마스터",
    "age": 25,
    "gender": "F"
}

###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "chef@test.com",
    "password": "password123"
}

###
GET {{baseUrl}}/auth/my
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJjaGVmQHRlc3QuY29tIiwiaWF0IjoxNzY5NDQyMDMxLCJleHAiOjE3Njk0NDU2MzF9.ijqMgotQtysKTGIK79zfPwRWSaHbDHU6g7Y2G5RnUsE

### 
POST {{baseUrl}}/ingredients
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJjaGVmQHRlc3QuY29tIiwiaWF0IjoxNzY5NDQyMDMxLCJleHAiOjE3Njk0NDU2MzF9.ijqMgotQtysKTGIK79zfPwRWSaHbDHU6g7Y2G5RnUsE

{
    "name": "삼겹살",
    "category": "meat",
    "quantity": "600",
    "expiry_date": "2026-01-30"
}

###
GET {{baseUrl}}/ingredients
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJjaGVmQHRlc3QuY29tIiwiaWF0IjoxNzY5NDQyMDMxLCJleHAiOjE3Njk0NDU2MzF9.ijqMgotQtysKTGIK79zfPwRWSaHbDHU6g7Y2G5RnUsE

###
PUT {{baseUrl}}/ingredients/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJjaGVmQHRlc3QuY29tIiwiaWF0IjoxNzY5NDQyMDMxLCJleHAiOjE3Njk0NDU2MzF9.ijqMgotQtysKTGIK79zfPwRWSaHbDHU6g7Y2G5RnUsE

{
    "quantity": "300",
    "expiry_date": "2026-02-05"
}

### 
DELETE {{baseUrl}}/ingredients/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJjaGVmQHRlc3QuY29tIiwiaWF0IjoxNzY5NDQyMDMxLCJleHAiOjE3Njk0NDU2MzF9.ijqMgotQtysKTGIK79zfPwRWSaHbDHU6g7Y2G5RnUsE