@baseUrl = http://localhost:3000/api

POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
    "email": "chef@test.com",
    "password": "password123",
    "nickname": "마스터",
    "age": 25,
    "gender": "F"
}

###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "chef@test.com",
    "password": "password123"
}

###
GET {{baseUrl}}/auth/my
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJjaGVmQHRlc3QuY29tIiwiaWF0IjoxNzY5NDQyMDMxLCJleHAiOjE3Njk0NDU2MzF9.ijqMgotQtysKTGIK79zfPwRWSaHbDHU6g7Y2G5RnUsE

### 
GET {{baseUrl}}/ingredients
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJjaGVmQHRlc3QuY29tIiwiaWF0IjoxNzY5NDQyMDMxLCJleHAiOjE3Njk0NDU2MzF9.ijqMgotQtysKTGIK79zfPwRWSaHbDHU6g7Y2G5RnUsE

###
POST {{baseUrl}}/chat
Content-Type: application/json

{
    "ingredients": ["계란", "파"],
    "prompt": "간단한 국 요리 추천해줘"
}