@baseUrl = http://localhost:3001

POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
    "email": "chef@test.com",
    "password": "password123",
    "nickname": "마스터",
    "age": 25,
    "gender": "F"
}

###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "chef@test.com",
    "password": "password123"
}

###
GET {{baseUrl}}/auth/my
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJjaGVmQHRlc3QuY29tIiwiaWF0IjoxNzY5NTc2OTg3LCJleHAiOjE3Njk1ODA1ODd9.3Yf2uEjlDMmpeLhHcBrVuwZgendB5U9sduNDOTXjZRw
### 
POST {{baseUrl}}/ingredients
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJjaGVmQHRlc3QuY29tIiwiaWF0IjoxNzY5NTc2OTg3LCJleHAiOjE3Njk1ODA1ODd9.3Yf2uEjlDMmpeLhHcBrVuwZgendB5U9sduNDOTXjZRw

{
    "name": "삼겹살",
    "category": "meat",
    "quantity": "600",
    "expiry_date": "2026-01-30"
}

###
GET {{baseUrl}}/ingredients
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJjaGVmQHRlc3QuY29tIiwiaWF0IjoxNzY5NTc2OTg3LCJleHAiOjE3Njk1ODA1ODd9.3Yf2uEjlDMmpeLhHcBrVuwZgendB5U9sduNDOTXjZRw

###
PUT {{baseUrl}}/ingredients/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJjaGVmQHRlc3QuY29tIiwiaWF0IjoxNzY5NTc2OTg3LCJleHAiOjE3Njk1ODA1ODd9.3Yf2uEjlDMmpeLhHcBrVuwZgendB5U9sduNDOTXjZRw

{
    "quantity": "300",
    "expiry_date": "2026-02-05"
}

### 
DELETE {{baseUrl}}/ingredients/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJjaGVmQHRlc3QuY29tIiwiaWF0IjoxNzY5NTc2OTg3LCJleHAiOjE3Njk1ODA1ODd9.3Yf2uEjlDMmpeLhHcBrVuwZgendB5U9sduNDOTXjZRw
###
POST {{baseUrl}}/chat
Content-Type: application/json

{
  "mode": "fridge",
  "ingredients": ["계란", "파", "스팸"],
  "cuisine": "한식"
}